### ISSUE TITLE
No enum constant org.bukkit.Statistic.PLAYERS_KILLED

### ISSUE THREAD

**Issue by Lammendam** [PlaceholderAPI/Statistics-Expansion#11]
When i use %statistic_player_kills% placeholder, i get error to console:
`[12:39:56] [Craft Scheduler Thread - 63/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Statistic.PLAYERS_KILLED
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at java.lang.Enum.valueOf(Enum.java:238)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at org.bukkit.Statistic.valueOf(Statistic.java:9)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onPlaceholderRequest(StatisticsExpansion.java:169)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:374)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at codecrafter47.bungeetablistplus.bukkitbridge.placeholderapi.PlaceholderAPIDataAccess.lambda$new$0(PlaceholderAPIDataAccess.java:38)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.lambda$onMessage$1(AbstractBridge.java:206)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:39:56] [Craft Scheduler Thread - 63/WARN]: 	at java.lang.Thread.run(Thread.java:748)`
Statistic expansion version: 1.9.2
Paper 1.14.4

**Comment by Andre601** [comment]
Please...
1. Use one of the issue-templates and
2. Report this to the [actual repository](https://github.com/PlaceholderAPI/Statistics-Expansion)

**Comment by aBooDyy** [comment]
Hello @Lammendam,
Are you sure that you got the latest version (v1.9.2) `/papi info Statistic`? 
Redownload it by running:
```
/papi ecloud download Statistic
/papi reload
```

And try again. I've just tried it and its working fine.
Let me know how to goes for you.


> 2. Report this to the [actual repository](https://github.com/PlaceholderAPI/Statistics-Expansion)

Thanks for your concern, It's in the correct repository.

**Comment by Lammendam** [comment]
I don't know what went wrong, but redownloading doesn't do any effect until I reboot my server. It seems strange and misleading to me. After second reboot it works fine for me too.
Thank you for your response.
