### ISSUE TITLE
Statistic Error

### ISSUE THREAD

**Issue by zikehalil4** [PlaceholderAPI/Statistics-Expansion#14]
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Enum.valueOf(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at org.bukkit.Statistic.valueOf(Statistic.java:1)
[11:54:27] [pool-15-thread-2/WARN]:     at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onPlaceholderRequest(StatisticsExpansion.java:169)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:257)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:220)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:427)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:185)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Configs$1.get(Configs.java:147)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.getValue(PlayerPlaceholder.java:26)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:25)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:84)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter.refreshHeaderFooter(HeaderFooter.java:34)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter$1.run(HeaderFooter.java:16)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Shared$2.run(Shared.java:167)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Thread.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Statistic.PLAYER_K?LLS
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Enum.valueOf(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at org.bukkit.Statistic.valueOf(Statistic.java:1)
[11:54:27] [pool-15-thread-2/WARN]:     at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onPlaceholderRequest(StatisticsExpansion.java:169)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:257)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:220)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:427)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:185)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Configs$1.get(Configs.java:147)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.getValue(PlayerPlaceholder.java:26)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:25)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:84)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter.refreshHeaderFooter(HeaderFooter.java:34)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter$1.run(HeaderFooter.java:16)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Shared$2.run(Shared.java:167)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Thread.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Statistic.PLAYER_K?LLS
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Enum.valueOf(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at org.bukkit.Statistic.valueOf(Statistic.java:1)
[11:54:27] [pool-15-thread-2/WARN]:     at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onPlaceholderRequest(StatisticsExpansion.java:169)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:257)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:220)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:427)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:185)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Configs$1.get(Configs.java:147)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.getValue(PlayerPlaceholder.java:26)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:25)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:84)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter.refreshHeaderFooter(HeaderFooter.java:34)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter$1.run(HeaderFooter.java:16)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Shared$2.run(Shared.java:167)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Thread.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Statistic.PLAYER_K?LLS
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Enum.valueOf(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at org.bukkit.Statistic.valueOf(Statistic.java:1)
[11:54:27] [pool-15-thread-2/WARN]:     at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onPlaceholderRequest(StatisticsExpansion.java:169)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:257)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:220)
[11:54:27] [pool-15-thread-2/WARN]:     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:427)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:185)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Configs$1.get(Configs.java:147)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.getValue(PlayerPlaceholder.java:26)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:25)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:84)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter.refreshHeaderFooter(HeaderFooter.java:34)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.HeaderFooter$1.run(HeaderFooter.java:16)
[11:54:27] [pool-15-thread-2/WARN]:     at me.neznamy.tab.shared.Shared$2.run(Shared.java:167)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]:     at java.lang.Thread.run(Unknown Source)
[11:54:27] [pool-15-thread-2/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Statistic.PLAYER_K?LLS

**Comment by Starmism** [comment]
`PLAYER_K?LLS` is not a valid statistic.
