### ISSUE TITLE
PlaceholderAPI (Statistic) does not work.

### ISSUE THREAD

**Issue by maksorr2** [PlaceholderAPI/Statistics-Expansion#38]
[PlaceholderAPI] Failed to load expansion class StatisticsExpansion - One of its properties is null which is not allowed! 
java.lang.NullPointerException: The expansion version is null! 
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_312] 
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:181) ~[?:?] 
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312] 
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_312] 
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_312] 
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312] 
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312] 
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_312] 
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312] 
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_312] 
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:350) ~[?:?] 
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?] 
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:76) [CraftTask.class:1.7.10-5.4] 
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [CraftScheduler.class:1.7.10-5.4] 
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?] 
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?] 
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?] 
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?] 
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by maksorr2** [comment]
Core - Crucible
Version - 1.7.10
